"use client";
import ClothingDiscovery from "./ClothingDiscovery";
import {useState} from "react";
import {Plus,Trash2} from "lucide-react";
import type {Garment,Reference} from "@/lib/types";
import {api,Empty,Modal,upload} from "./ui";
export default function Spotter({garments,references,onRefresh,onAuth,authenticated}:{garments:Garment[];references:Reference[];onRefresh:()=>Promise<void>;onAuth:()=>void;authenticated:boolean}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 return <div className="stack"><ClothingDiscovery authenticated={authenticated} onAuth={onAuth} onRefresh={onRefresh}/><div className="section-heading"><div><h2>Spotted. Saved. Styled.</h2><p>Turn inspiration into a look you own.</p></div><button aria-label="Add inspiration" className="icon-button primary" onClick={()=>authenticated?setOpen(true):onAuth()}><Plus size={20}/></button></div><div className="note">Save an outfit photo and pair it with pieces from your closet. Use photos you own or have permission to save.</div>{!references.length?<Empty title="Your inspiration lives here" action={<button onClick={()=>authenticated?setOpen(true):onAuth()}>Add your first reference</button>}>That outfit you keep thinking about? Give it a home, then recreate it your way.</Empty>:<div className="garment-grid">{references.map(r=><article className="garment-card" key={r.id}><img className="reference-photo" src={r.imageUrl} alt={r.name}/><h3>{r.name}</h3><p>{r.garmentIds.map(id=>garments.find(g=>g.id===id)?.name).filter(Boolean).join(" · ")||"No closet pieces paired"}</p><button className="text-button danger" disabled={busy} onClick={async()=>{if(!confirm("Delete this inspiration photo?"))return;setBusy(true);setError("");try{await api(`/api/references/${r.id}`,"DELETE");await onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Trash2 size={15}/>Delete reference</button></article>)}</div>}{error&&<p className="error" role="alert">{error}</p>}{open&&<Modal title="Save your inspiration" onClose={()=>{if(!busy)setOpen(false);}}><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const imageUrl=await upload(f.get("photo") as File);await api("/api/references","POST",{name:f.get("name"),imageUrl,garmentIds:f.getAll("garmentIds")});await onRefresh();setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Name<input name="name" required maxLength={100}/></label><label>Inspiration photo<input name="photo" type="file" required accept="image/jpeg,image/png,image/webp"/></label><small>JPG, PNG or WebP · up to 4 MB.</small><fieldset><legend>Pair with your pieces</legend><div className="checklist">{garments.map(g=><label key={g.id}><input type="checkbox" name="garmentIds" value={g.id}/><img src={g.imageUrl} alt=""/>{g.name}</label>)}</div>{!garments.length&&<p>Add closet pieces later to start recreating your inspiration.</p>}</fieldset>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary">{busy?"Saving…":"Save reference"}</button></form></Modal>}</div>;
}
